### ISSUE TITLE
update failed for AnAction with ID=idea.plugins.thirdparty.filecompletion.share.OpenFileInExternalToolAction

### ISSUE THREAD

**Issue by aristotll** [venkato/ideafilecompletion#1]
```
update failed for AnAction with ID=idea.plugins.thirdparty.filecompletion.share.OpenFileInExternalToolAction
java.lang.NullPointerException
	at idea.plugins.thirdparty.filecompletion.jrr.actions.openfile.OpenFileInExternalToolActionImpl.getPlace(OpenFileInExternalToolActionImpl.groovy:138)
	at idea.plugins.thirdparty.filecompletion.jrr.actions.openfile.OpenFileInExternalToolActionImpl.update(OpenFileInExternalToolActionImpl.groovy:103)
	at idea.plugins.thirdparty.filecompletion.share.DeligateAction.update(DeligateAction.groovy:29)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:131)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:234)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:179)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:99)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:340)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:98)
	at com.intellij.openapi.editor.impl.EditorImpl.a(EditorImpl.java:4443)
	at com.intellij.openapi.editor.impl.EditorImpl.access$9500(EditorImpl.java:135)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.g(EditorImpl.java:3491)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mousePressed(EditorImpl.java:3414)
	at java.awt.Component.processMouseEvent(Component.java:6538)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.k(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:651)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by venkato** [comment]
Hi, it is failed on log statement . Will fix this or next week.

**Comment by venkato** [comment]
Fixed. Please update plugin. 
Feedback welcome
